### ISSUE TITLE
How to use the code for Custom dataset  

### ISSUE THREAD

**Issue by Alamnoor** [sailab-code/gnn#11]
Can I ask how you create the *.mat files and which function did you used? I need to use your code for the custom data but I am facing the problems of the *.mat files. It will be more visible for research community. Please comment if possible. Thanks ~

**Comment by mtiezzi** [comment]
Hi,
the *.mat file were imported from the [original MATLAB implementation of GNN ](https://www3.diism.unisi.it/~franco/Research/GNNDownload.php). The subgraph/clique examples use the data provided by the original MATLAB code to reproduce the experiments of the original paper.

If you want to use custom data, we provide the **EN Input format**, which is [described in the documentation ](https://mtiezzi.github.io/gnn_site/tutorial.html#enmatrices). 

See the [Tensorflow tutorial ](https://mtiezzi.github.io/gnn_site/tutorial.html#), but also two examples available on this repository using the EN input format:

1.[ Simple example](https://github.com/sailab-code/gnn/blob/master/examples/GNN_simple.py) (devised in order to understaind the EN input format)
2. [Karate Club example](https://github.com/sailab-code/gnn/blob/master/examples/GNN_Karate.py)

**Comment by Alamnoor** [comment]
> Hi,
> the *.mat file were imported from the [original MATLAB implementation of GNN ](https://www3.diism.unisi.it/~franco/Research/GNNDownload.php). The subgraph/clique examples use the data provided by the original MATLAB code to reproduce the experiments of the original paper.
> 
> If you want to use custom data, we provide the **EN Input format**, which is [described in the documentation ](https://mtiezzi.github.io/gnn_site/tutorial.html#enmatrices).
> 
> See the [Tensorflow tutorial ](https://mtiezzi.github.io/gnn_site/tutorial.html#), but also two examples available on this repository using the EN input format:
> 
> 1.[ Simple example](https://github.com/sailab-code/gnn/blob/master/examples/GNN_simple.py) (devised in order to understaind the EN input format)
> 2. [Karate Club example](https://github.com/sailab-code/gnn/blob/master/examples/GNN_Karate.py)

Thank you so much for the response with detail description. It helped in my progress. I am still trying to prepare my data according to train with the Mutag_GNN.py. Thanks
